/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/takoyaki.glb -o src/components/Takoyaki.jsx -k -K -r public 
*/

import {React, useRef} from 'react'

import { useAtom } from "jotai";
import { Html,useGLTF, useAnimations } from '@react-three/drei'
import { currentPageAtom } from "./UI";

const OverlayItem = ({
  className = "",
  title,
  description,
  price,
  bgColor,
  ...props
}) => {
  const [currentPage] = useAtom(currentPageAtom);
  return (
    <Html
      transform
      distanceFactor={1.2}
      center
      className={`w-48 rounded-md overflow-hidden ${
        currentPage === "store" ? "" : "opacity-0"
      } transition-opacity duration-1000 ${className}`}
      {...props}
    >
      <div className="bg-white bg-opacity-50 backdrop-blur-lg text-xs p-2 w-full">
        <h2 className="font-bold">{title}</h2>
        <p>{description}</p>
      </div>
      <button
        className={`${bgColor} hover:bg-opacity-50 transition-colors duration-500 px-4 py-2 font-bold text-white w-full text-xs`}
      >
        Add to cart ${price}
      </button>
    </Html>
  );
};

export function Takoyaki(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/takoyaki.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" />
        <group name="Cube021_SurfaceDrawing" />
        <group name="Cube021_SurfaceDrawing001" />
        <group name="Cube009_SurfaceDrawing" />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials.房子} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials.房子} />
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials.屋顶} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials.房子} />
        <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials.房子} />
        <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials.房子} />
        <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials.房子} />
        <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials.屋顶} position={[-0.007, 0, 0.001]} />
        <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials.房子} />
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials.房子} />
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials.房子} />
        <group name="Cylinder007">
          <mesh name="Cylinder010_1" geometry={nodes.Cylinder010_1.geometry} material={materials.beer} />
          <mesh name="Cylinder010_2" geometry={nodes.Cylinder010_2.geometry} material={materials['Material.003']} />
        </group>
        <group name="beer">
          {/* <OverlayItem
            title={'Beer'} price={"33"} bgColor={'bg-yellow-500'} className={'translate delay-1000'}
            scale = {4}
            position-y ={4}
            position-x ={-2}
            position-z = {3}
          ></OverlayItem> */}
          <mesh name="Cylinder011_1" geometry={nodes.Cylinder011_1.geometry} material={materials.beer} />
          <mesh name="Cylinder011_2" geometry={nodes.Cylinder011_2.geometry} material={materials['Material.003']} />
        </group>
        <mesh name="Retopo_Cube036" geometry={nodes.Retopo_Cube036.geometry} material={materials['Material.023']}>
          <group name="Retopo_Cube036_SurfaceDrawing" />
        </mesh>
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.022']} position={[0.003, 0.375, 0.094]} scale={0.905} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials.屋顶} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.屋顶} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.屋顶} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.屋顶} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.屋顶} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.屋顶} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.房子} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.房子} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.014']} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.005']} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Candlewax.004']} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.屋顶} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.房子} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.屋顶} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials.屋顶} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.Material} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.009']} />
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.009']} />
        <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['Material.009']} />
        <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['Material.009']} />
        <mesh name="Cylinder008" geometry={nodes.Cylinder008.geometry} material={materials['Material.020']} />
        <group name="Sphere001">
          <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.009']} />
          <mesh name="Sphere002_1" geometry={nodes.Sphere002_1.geometry} material={materials['Material.005']} />
        </group>
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['Material.008']} />
        <group name="takoyaki">
          <mesh name="Sphere004_1" geometry={nodes.Sphere004_1.geometry} material={materials['Material.009']} />
          <mesh name="Sphere004_2" geometry={nodes.Sphere004_2.geometry} material={materials['Material.005']} />
        </group>
        <group name="Sphere004">
          <mesh name="Sphere012" geometry={nodes.Sphere012.geometry} material={materials['Material.012']} />
          <mesh name="Sphere012_1" geometry={nodes.Sphere012_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="Sphere006">
          <mesh name="Sphere013" geometry={nodes.Sphere013.geometry} material={materials['Material.012']} />
          <mesh name="Sphere013_1" geometry={nodes.Sphere013_1.geometry} material={materials['Material.003']} />
        </group>
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Material.001']} />
        <group name="Sphere007">
          <mesh name="Sphere014" geometry={nodes.Sphere014.geometry} material={materials['Material.006']} />
          <mesh name="Sphere014_1" geometry={nodes.Sphere014_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="octupus">
          <mesh name="Sphere016" geometry={nodes.Sphere016.geometry} material={materials['little octupus']}
           />
           <OverlayItem
            title={'Takoyaki'} price={"8"} bgColor={'bg-yellow-500'} className={'translate delay-1000'}
            scale = {4}
            description={'A delicious Takoyaki'}
            position-y ={4}
            position-x ={3}
            position-z = {3}
          ></OverlayItem>
          <mesh name="Sphere016_1" geometry={nodes.Sphere016_1.geometry} material={materials['Material.003']} />
        </group>
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials.房子} />
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials.Candlewax} position={[-0.014, 0, -0.001]} />
        <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials['Candlewax.004']} />
        <mesh name="Retopo_Cube037" geometry={nodes.Retopo_Cube037.geometry} material={materials['Material.017']}>
          <group name="Retopo_Cube037_SurfaceDrawing" />
        </mesh>
        <mesh name="Cone" geometry={nodes.Cone.geometry} material={materials['Material.005']} />
        <mesh name="Sphere008" geometry={nodes.Sphere008.geometry} material={materials['Material.024']} />
        <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={nodes.Cylinder011.material} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.005']} />
        <group name="Cylinder012">
          <mesh name="Cylinder012_1" geometry={nodes.Cylinder012_1.geometry} material={materials.olio} />
          <mesh name="Cylinder012_2" geometry={nodes.Cylinder012_2.geometry} material={materials['Material.004']} />
        </group>
        <mesh name="Curve001" geometry={nodes.Curve001.geometry} material={materials['Material.021']} />
        <mesh name="Retopo_Cube003" geometry={nodes.Retopo_Cube003.geometry} material={materials['Material.019']}>
          <group name="Retopo_Cube003_SurfaceDrawing" />
        </mesh>
        <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Material.009']} />
        <group name="Retopo_Cube019">
          <mesh name="mesh003" geometry={nodes.mesh003.geometry} material={materials['Material.007']} />
          <mesh name="mesh003_1" geometry={nodes.mesh003_1.geometry} material={materials['Material.003']} />
        </group>
        <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials['Material.009']} />
        <group name="Cube009" position={[0, -0.384, 0]}>
          <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={materials['Material.009']} />
          <mesh name="Cube042_1" geometry={nodes.Cube042_1.geometry} material={materials['Material.010']} />
        </group>
        <group name="Cube038">
          <mesh name="Cube044" geometry={nodes.Cube044.geometry} material={materials['Material.009']} />
          <mesh name="Cube044_1" geometry={nodes.Cube044_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="Retopo_Cube001">
          <mesh name="mesh002" geometry={nodes.mesh002.geometry} material={materials['Material.007']} />
          <mesh name="mesh002_1" geometry={nodes.mesh002_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="Cylinder001" position={[4.593, 0.842, -2.455]}>
          <mesh name="Cylinder013" geometry={nodes.Cylinder013.geometry} material={materials.olio} />
          <mesh name="Cylinder013_1" geometry={nodes.Cylinder013_1.geometry} material={materials['Material.004']} />
        </group>
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.房子} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/takoyaki.glb')
